---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 12.2.1

provisioner:
  name: chef_zero
  attributes:
    firewall:
      allow_ssh: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[rackspace_firewall::default]
